### ISSUE TITLE
Example of ECB encrypt and decrypt, both allowing user inputs

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/Cryptoflow#4]
Should allow users to input the message m and key k for the encrypt, manually change the input of the decrypt to ciphertext c and key k, to see the message come out again.

**Comment by hypesystem** [comment]
@Bladtman242 interested?

**Comment by Bladtman242** [comment]
[I suppose so](https://github.com/hypesystem/Cryptoflow/pull/5) :)
